name: build docker
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-npm-install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name : setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: run install
        shell: bash
        run: |
          npm install
          npm test

  docker-build:
    needs: run-npm-install
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - run: |
          docker build -t ${{ github.sha }} .
