name: Warning Test the Lab 3 of Code
on:
  push:
    branches:
      - master
jobs:
  test-interactions-lab1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install action dependencies
        run: npm install
        working-directory: .github/actions/summary_ex4

      - name: Build the action (prepare)
        run: npm run prepare
        working-directory: .github/actions/summary_ex4


      - uses: ./.github/actions/summary_ex4
